# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/bss_office_facade/v1/bss_office_facade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/bss_office_facade/v1/bss_office_facade.proto',
  package='ozonmp.bss_office_facade.v1',
  syntax='proto3',
  serialized_options=_b('ZKgithub.com/ozonmp/bss-office-facade/pkg/bss-office-facade;bss_office_facade'),
  serialized_pb=_b('\n3ozonmp/bss_office_facade/v1/bss_office_facade.proto\x12\x1bozonmp.bss_office_facade.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n\rOfficePayload\x12\x17\n\x02id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x02id\x12\x1d\n\x04name\x18\x02 \x01(\tB\t\xfa\x42\x06r\x04\x10\x02\x18\x64R\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\"\xb5\x02\n\x0bOfficeEvent\x12\x17\n\x02id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x02id\x12$\n\toffice_id\x18\x02 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x08officeId\x12\x16\n\x06status\x18\x03 \x01(\x04R\x06status\x12\x1d\n\x04type\x18\x04 \x01(\tB\t\xfa\x42\x06r\x04\x10\x02\x18\x64R\x04type\x12\x34\n\x07\x63reated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\x12\x34\n\x07updated\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07updated\x12\x44\n\x07payload\x18\x07 \x01(\x0b\x32*.ozonmp.bss_office_facade.v1.OfficePayloadR\x07payloadBMZKgithub.com/ozonmp/bss-office-facade/pkg/bss-office-facade;bss_office_facadeb\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_OFFICEPAYLOAD = _descriptor.Descriptor(
  name='OfficePayload',
  full_name='ozonmp.bss_office_facade.v1.OfficePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.bss_office_facade.v1.OfficePayload.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ozonmp.bss_office_facade.v1.OfficePayload.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\006r\004\020\002\030d'), json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ozonmp.bss_office_facade.v1.OfficePayload.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='description', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=277,
)


_OFFICEEVENT = _descriptor.Descriptor(
  name='OfficeEvent',
  full_name='ozonmp.bss_office_facade.v1.OfficeEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='office_id', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.office_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='officeId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.status', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='status', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\006r\004\020\002\030d'), json_name='type', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.created', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='created', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.updated', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='updated', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='ozonmp.bss_office_facade.v1.OfficeEvent.payload', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='payload', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=589,
)

_OFFICEEVENT.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OFFICEEVENT.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OFFICEEVENT.fields_by_name['payload'].message_type = _OFFICEPAYLOAD
DESCRIPTOR.message_types_by_name['OfficePayload'] = _OFFICEPAYLOAD
DESCRIPTOR.message_types_by_name['OfficeEvent'] = _OFFICEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OfficePayload = _reflection.GeneratedProtocolMessageType('OfficePayload', (_message.Message,), dict(
  DESCRIPTOR = _OFFICEPAYLOAD,
  __module__ = 'ozonmp.bss_office_facade.v1.bss_office_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_office_facade.v1.OfficePayload)
  ))
_sym_db.RegisterMessage(OfficePayload)

OfficeEvent = _reflection.GeneratedProtocolMessageType('OfficeEvent', (_message.Message,), dict(
  DESCRIPTOR = _OFFICEEVENT,
  __module__ = 'ozonmp.bss_office_facade.v1.bss_office_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_office_facade.v1.OfficeEvent)
  ))
_sym_db.RegisterMessage(OfficeEvent)


DESCRIPTOR._options = None
_OFFICEPAYLOAD.fields_by_name['id']._options = None
_OFFICEPAYLOAD.fields_by_name['name']._options = None
_OFFICEEVENT.fields_by_name['id']._options = None
_OFFICEEVENT.fields_by_name['office_id']._options = None
_OFFICEEVENT.fields_by_name['type']._options = None
# @@protoc_insertion_point(module_scope)
